### ISSUE TITLE
Assign Roles to Team Members

### ISSUE THREAD

**Issue by krishnapriya-n** [krishnapriya-n/VCT-Hackathon#1]
## Description
We need to finalize and assign roles for each team member based on their skills and the tasks required for the project. Below is a list of the roles that need to be filled. Please comment with your preferred role and any secondary responsibilities you'd like to take on.

## Proposed Roles
- <b>Project Manager/ Team Lead:</b>
    - Responsibilities: Oversee project progress, manage communication, ensure deadlines are met. <a href = "https://github.com/krishnapriya-n/VCT-Hackathon/blob/04dd4329e00a067693f84de9cafd1b615217e457/docs/rules.md?plain=1#L17"> Check rules.md </a>
- <b>Machine Learning Engineer:</b>
    - Responsibilities: Build and fine-tune the language model, integrate LLM into the assistant.
- <b>Backend Developer / Data Engineer</b>
   -  Responsibilities: Develop backend architecture, integrate data from Riot Games' API.

## Additional Roles (Optional)
- UI/UX Design
- Data Preprocessing
- Cloud Deployment (AWS)
- Documentation & Methodology Write-Up
- Testing & Quality Assurance
- Demo Video Creation

The roles listed above are suggestions based on the project’s needs, but feel free to suggest any other role you'd prefer to take on or explore. We're flexible and happy to adjust roles to match your interests and strengths. Let's make sure everyone is comfortable with their responsibilities.

### Note
As we are a team of three, it's expected that we'll help each other across different tasks. However, the assigned role will represent your primary responsibility for the project.

**Comment by krishnapriya-n** [comment]
I am happy to take the role of Project Manager, along with Documentation and Methodology Write-Up.

**Comment by krishnapriya-n** [comment]
@enmadourayuga agreed to be Machine Learning Engineer, project charter has been updated accordingly. Looking to hear from @Annihilator2860 soon.

**Comment by Annihilator2860** [comment]
Hi, i would like to do Testing and Quality Assurance and Demo Video Creation.

**Comment by krishnapriya-n** [comment]
Amazing, closing issue #1 as completed on 09/09/2024 by all team members.
