### ISSUE TITLE
Development Tools

### ISSUE THREAD

**Issue by krishnapriya-n** [krishnapriya-n/VCT-Hackathon#5]
Before we start coding, we need to agree on which development tools we'll use to ensure smooth collaboration. Let’s discuss and decide on the following tools:

### Code Editor/IDE
Examples: VS Code, PyCharm, Sublime Text, etc.
Please comment on your preferred code editor.

### Communication Platform
Comment if we would like to start using Discord or any other application to communicate regarding the project..

### Project Management
We are using GitHub issues and <a href = "https://github.com/krishnapriya-n/VCT-Hackathon/tree/main/schedules">schedules</a> for managing issues so far, but if anyone prefers something else like Trello or Notion, feel free to suggest it.

### Other Tools
Would you like to implement any other applications that would like to help with the project?

**Comment by Annihilator2860** [comment]
I have used VS Code before so I would say I'm confident with it. As for communication and weekly meetings, I think Discord would work nicely as we can save our work done there too.

**Comment by enmadourayuga** [comment]
I have VS Code as well,I agree with the above person so lets go with discord.

**Comment by krishnapriya-n** [comment]
Added Discord Server. Decided to go with VS Code.
